language: haskell
install:
  - npm install -g elm
  - elm-package install -y
cache:
  directories:
    - elm-stuff/build-artifacts

script:
  - alias gsed=sed
  - make

notifications:
  slack:
    secure: 0zH9mGjipdI9it6RZRTJlGuehphO1mmxtRQtu5ahDY86dGG9qaUfktzBsBNDzd9JzwixCplXV8TiZVLjp166sBsKd6iHLaTbiMTdHVWlR4bPHHnvkxX5DaOMylmVU4xNgckdc8EiKEbrP1fUolE5zK083NrPHrE44Ldv1YvebWNE3tDWrYvOTa9CzxwC9BtdNbUhdJSH9o0Eqn25nVjq4uqmIDCsBP7AFIVAMk65GglUPxgIMpX4Ys/rwVyQJOgnmvqLfX7gu32IQgc7zAK9uIqVfZIUjAxc21Fdcm9tLdqtqPLSbfju6MEWLqn8wndTrDGLsin+oGdPyyVx5EoNC6BbN/gzoD2dQ/ra1zaCAUTsIPgopyjjU8oPyqyfemJ1TDkV5bXoQSW3gmeFPzwdYVoT4BaXa95nNn1cpbJyPsNHGvedgssL9KZaHQx3a0YxkwjMZ5+QnbdhAKVDAso1D820sUXxl5MCGuswHaeWOv0kAO7/Etd8S5I4X1JHMIyCc/gAafOS4I4HnGFqPcAgytRpIynKiquTXqVRSoxCiwZmbS584Vf84LhHj0M8ab0OKY5OLbRmaGGwWbmKNJzclGBLqd5NiJdm6MHb/oMTDzRyqKkNPTQ6gHsdnNjNOLwdEaZbo1j6mj2IswjyMvRX8zxGM/dzplOPR9iNzU6Y6hk=
